---
title: "change ponit detection example"
author: "Huang Xinrui"
date: "2022-12-14"
output: html_document
---
```{r}
devtools::install_github("yudan121/susie")
library(susie)
```

# define change-points
```{r}
set.seed(2)
num = 6
t_set = sample(30:100, num)
t_set
```

# generate y
```{r}
set.seed(10)
y_value = round(runif(num, -1.2, 1.5), 2)
y_value
```

```{r}
set.seed(1)
y0 = rep(y_value, times = t_set)
l = length(y0)
y0 = y0 + rnorm(l, 0, 0.1)
```

```{r}
png("gt.png")
plot(1:l, y0, cex = 1, xlab = "variable", ylab = "value", main = "ground truth") 
pos = c(1, cumsum(t_set))
for(i in 1:num){
  if(i < num){
    abline(v = pos[i + 1], col = "red", lwd = 1.5)
  }
  segments(x0 = pos[i], y0 = y_value[i], x1 = pos[i + 1], y1 = y_value[i], col = "blue", cex = 1, lwd = 2)
}
```

# design X
```{r}
X = matrix(0, ncol = l - 1, nrow = l)
for(i in 1:(l - 1)){
  X[(i + 1):l, i] = 1
}
# standardize
y = (y0 - mean(y0))/sqrt(var(y0))
for(i in 1:(l - 1)){
  X[, i] = (X[, i] - mean(X[,i]))/sqrt(var(X[, i]))
}
```

# try different parameter settings
```{r}
#sigma2, sigma0_2 have big influence; L also plays a role
#parameters 1
test_1 = IBSS(X, y, 0.3, 1, num, 1)
test_5 = IBSS(X, y, 0.3, 1, num, 5)
#parameters 2
test_50 = IBSS(X, y, 0.5, 0.8, num, 5)
#parameters 3
test2_5 = IBSS(X, y, 0.3, 1, 10, 15)
```

# PIPs
```{r}
tt1 = PIP(test_1$alpha_mat)
tt5 = PIP(test_5$alpha_mat)
tt50 = PIP(test_50$alpha_mat)
tt2_5 = PIP(test2_5$alpha_mat)
sort(tt1, decreasing = TRUE)[1:20]
order(tt1,decreasing = TRUE)[1:10]
```

# Credible sets and purified credible sets
```{r}
cs1 = CredibleSet(test_1$alpha_mat, 0.9)
pure_cs1 = purify_cs(X, cs1, purity = 0.2)
cs5 = CredibleSet(test_5$alpha_mat, 0.9)
pure_cs5 = purify_cs(X, cs5, purity = 0.2)

cs50 = CredibleSet(test_50$alpha_mat, 0.9)
pure_cs50 = purify_cs(X, cs50, purity = 0.2)

cs2_5 = CredibleSet(test2_5$alpha_mat, 0.9)
#Since L becomes larger, we increase the purity bound correspondingly
pure_cs2_5 = purify_cs(X, cs2_5, purity = 0.7)
```

# Preparation for the plots
```{r}
df_pip1 = data.frame("variable" = 1:(l-1), "PIP" = tt1, "cs" = rep(0, l-1))
L = length(cs1)
for(i in 1:L){
  df_pip1$cs[cs1[[i]]] = i
}
df_pip1$cs = factor(df_pip1$cs)

df_pip5 = data.frame("variable" = 1:(l-1), "PIP" = tt5, "cs" = rep(0, l-1))
L = length(cs5)
for(i in 1:L){
  df_pip5$cs[cs5[[i]]] = i
}
df_pip5$cs = factor(df_pip5$cs)

df_pip50 = data.frame("variable" = 1:(l-1), "PIP" = tt50, "cs" = rep(0, l-1))
L = length(cs50)
for(i in 1:L){
  df_pip50$cs[cs50[[i]]] = i
}
df_pip50$cs = factor(df_pip50$cs)

df_pip2_5 = data.frame("variable" = 1:(l-1), "PIP" = tt2_5, "cs" = rep(0, l-1))
L = length(cs2_5)
for(i in 1:L){
  df_pip2_5$cs[cs2_5[[i]]] = i
}
df_pip2_5$cs = factor(df_pip2_5$cs)
```

```{r}
ndf_pip1 = data.frame("variable" = 1:(l-1), "PIP" = tt1, "cs" = rep(0, (l-1)))
L = length(pure_cs1)
if(L > 1){
  for(i in 1:L){
    ndf_pip1$cs[pure_cs1[[i]]] = i
  }
  ndf_pip1$cs = factor(ndf_pip1$cs)
}
ndf_pip1$cs = factor(ndf_pip1$cs)

ndf_pip5 = data.frame("variable" = 1:(l-1), "PIP" = tt5, "cs" = rep(0, (l-1)))
L = length(pure_cs5)
for(i in 1:L){
  ndf_pip5$cs[pure_cs5[[i]]] = i
}
ndf_pip5$cs = factor(ndf_pip5$cs)

ndf_pip50 = data.frame("variable" = 1:(l-1), "PIP" = tt50, "cs" = rep(0, (l-1)))
L = length(pure_cs50)
for(i in 1:L){
  ndf_pip50$cs[pure_cs50[[i]]] = i
}
ndf_pip50$cs = factor(ndf_pip50$cs)

ndf_pip2_5 = data.frame("variable" = 1:(l-1), "PIP" = tt2_5, "cs" = rep(0, (l-1)))
L = length(pure_cs2_5)
for(i in 1:L){
  ndf_pip2_5$cs[pure_cs2_5[[i]]] = i
}
ndf_pip2_5$cs = factor(ndf_pip2_5$cs)
```


# Show results under different iterations or parameter settings
```{r}
library(ggplot2)
```

```{r}
ggplot(data = df_pip1, aes(x = variable, y = PIP, color = cs)) + geom_point(aes(color = cs), alpha = 0.8) + scale_color_manual(values=c("grey", "blue", "red", "green", "yellow"))
```

```{r}
ggplot(data = ndf_pip1, aes(x = variable, y = PIP, color = cs)) + geom_point(aes(color = cs), alpha = 0.8) + scale_color_manual(values=c("grey", "blue", "red", "green", "yellow"))
ggsave("pcs1.png")
```

```{r}
ggplot(data = df_pip5, aes(x = variable, y = PIP, color = cs)) + geom_point(aes(color = cs), alpha = 0.8) + scale_color_manual(values=c("grey", "blue", "red", "green", "yellow", "pink"))
```

```{r}
ggplot(data = ndf_pip5, aes(x = variable, y = PIP, color = cs)) + geom_point(aes(color = cs), alpha = 0.8) + scale_color_manual(values=c("grey", "blue", "red", "green", "yellow", "pink"))
ggsave("pcs5.png")
```

```{r}
ggplot(data = df_pip50, aes(x = variable, y = PIP, color = cs)) + geom_point(aes(color = cs), alpha = 0.8) + scale_color_manual(values=c("grey", "blue", "red", "green", "yellow", "pink"))
```

```{r}
ggplot(data = ndf_pip50, aes(x = variable, y = PIP, color = cs)) + geom_point(aes(color = cs), alpha = 0.8) + scale_color_manual(values=c("grey", "blue", "red", "green", "yellow", "pink"))
ggsave("pcs3_50.png")
```

```{r}
ggplot(data = df_pip2_5, aes(x = variable, y = PIP, color = cs)) + geom_point(aes(color = cs), alpha = 0.8) + scale_color_manual(values=c("grey", "blue", "red", "green", "yellow", "pink"))
```

```{r}
ggplot(data = ndf_pip2_5, aes(x = variable, y = PIP, color = cs)) + geom_point(aes(color = cs), alpha = 0.8) + scale_color_manual(values=c("grey", "blue", "red", "green", "yellow", "pink"))
ggsave("pcs2_5.png")
```

```{r}
pos
pure_cs5
```

```{r}
plot(1:l, y0, cex = 1, xlab = "variable", ylab = "value", main = "90% purified credible sets") 
pos = c(1, cumsum(t_set))
for(i in 1:num){
  if(i <= length(pure_cs5)){
     abline(v = pure_cs5[[i]], col = rgb(255, 0, 0, 80, maxColorValue=255), lwd = 1.5)
  }
  segments(x0 = pos[i], y0 = y_value[i], x1 = pos[i + 1], y1 = y_value[i], col = "blue", cex = 1, lwd = 2)
}
```

```{r}
plot(1:l, y0, cex = 1, xlab = "variable", ylab = "value", main = "90% purified credible sets") 
pos = c(1, cumsum(t_set))
for(i in 1:num){
  if(i <= length(pure_cs50)){
     abline(v = pure_cs50[[i]], col = rgb(255, 0, 0, 80, maxColorValue=255), lwd = 1.5)
  }
  segments(x0 = pos[i], y0 = y_value[i], x1 = pos[i + 1], y1 = y_value[i], col = "blue", cex = 1, lwd = 2)
}
```

```{r}
plot(1:l, y0, cex = 1, xlab = "variable",  ylab = "value", main = "90% purified credible sets") 
pos = c(1, cumsum(t_set))
for(i in 1:num){
  if(i <= length(pure_cs2_5)){
     abline(v = pure_cs2_5[[i]], col = rgb(255, 0, 0, 80, maxColorValue=255), lwd = 1.5)
  }
  segments(x0 = pos[i], y0 = y_value[i], x1 = pos[i + 1], y1 = y_value[i], col = "blue", cex = 1, lwd = 2)
}
```
